### ISSUE TITLE
Checks for `master` should be required

### ISSUE THREAD

**Issue by OskarStark** [symfony-tools/symfony-translation-checker#27]
![CleanShot 2023-10-10 at 08 33 39@2x](https://github.com/symfony-tools/symfony-translation-checker/assets/995707/855d375c-ed16-4ccd-9c71-c0dbe361f416)

**Comment by Nyholm** [comment]
Ah. I was wondering why it wasn’t working. 
I set up rules for ‘main’. 

![IMG_5977](https://github.com/symfony-tools/symfony-translation-checker/assets/1275206/d8cc51e0-e234-433f-b923-c0b27023c464)

**Comment by OskarStark** [comment]
You could allow bots to push to master (down below in the config)

**Comment by OskarStark** [comment]
![CleanShot 2023-10-11 at 11 04 18@2x](https://github.com/symfony-tools/symfony-translation-checker/assets/995707/000d9305-509c-42f2-b2c8-de4ea0fc841b)
